### PR TITLE
Feature/contributors guide

### LINKED ISSUE #28: Add Setup Guide for Contributors to README
Enhance the README file to include a setup guide for new contributors, enabling them to quickly get started with the project. The setup guide should include instructions for setting up the development environment, installing dependencies, and running the project locally.

### PR DESCRIPTION
**Pull request by izzyyhh**
## What type of PR is this? (check all applicable)
- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ x] 📦 Chore
- [ ] ⏩ Revert

### CODE REVIEW

**Review by FabianUntermoser — DISMISSED** [review]
Great start @izzyyhh. I think we should merge this.

As mentioned I woud like to see further documentation on how to properly setup Strapi for basic features of this relaunch in order to be able to really start working with the application. Once documentation, automation should follow so that new developers have a working state and don't have to deal with manual steps.

**Comment by georgalis** [comment]
As a longtime vim user, thanks for all your efforts here!

I hope it is okay to drop a couple async comments:
* the sooner the CONTRIBUTING.md file is merged to main and linked from the default README.md the better... my initial purview of this project was derailed not knowing about the branching schema. It didn't occur to me that a website_next_generation repo would require me to navigate into any particular non-default branch, and that is still not on the default readme.
* the miro preview graphics are excellent! nice work! they remind me of the impressive project graphics management in use by neovim, worth a careful look. It is a large complex project, they use a separate repo for graphics files to avoid polluting the code repo with binaries, and the graphics are excellent breakouts of code api and component interaction.

**Comment by georgalis** [comment]
correction: s/neovim/neomutt/
https://github.com/neomutt/neomutt
https://github.com/neomutt/gfx
https://neomutt.org/
I don't have any good examples handy of how the graphics are linked from the markdown, but navigation of the gfx repo should whet your interest if you have not seen those illistrations before...

**Comment by FabianUntermoser** [comment]
I linked the contribution guide from the README and removed some duplicate info.

Keeping the documentation / design files closer to the repo is a good point.
I don't have access to the design files, but perhaps there's a way to share the adobe XD images through a link, 
which could be inlined in markdown like this `img`. This would only work as long as the link is valid though.

I can't comment on the branch strategy, but I agree it unnecessarily hides the development efforts of this project.

**Comment by muru** [comment]
Is there anything blocking this PR from being merged? (Or at least, anything that random drive-by contributions by people not in the core dev team could fix?)

**Comment by izzyyhh** [comment]
> Is there anything blocking this PR from being merged? (Or at least, anything that random drive-by contributions by people not in the core dev team could fix?)

Not really, waiting for approval. Every contribution is helpful!

**Pull request merged**
