### PR TITLE
docu(README) => Add getting started section in readme

### PR DESCRIPTION
**Pull request by hanEck**
## Description
Add Getting started section in README file

## What type of PR is this? (check all applicable)
- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore
- [ ] ⏩ Revert

### CODE REVIEW

**Comment by FabianUntermoser** [comment]
Here's some personal suggestions for improving the current README:

General
- Add a showcase (link to the latest deployed version, or a demo instance)
- Link to a Contributors Guideline if you have one

Getting Started
- list pre-requisites and required dependencies (docker, ...)
- List commands on how to run the latest release (ideally a single command, i.e latest ready to go docker image to use instead of having to build locally ...)

Build Section
- List commands to build the entire application (ideally a single command)
- Note which port the application is running on for convenience

Also, use markdown format to properly indicate shell commands. Like this

```sh
docker compose -f docker-compose.local.yml up

# or more simply when using make
make build
```

**Comment by manuel-pross** [comment]
I agree with @FabianUntermoser 

Maybe ask @jomunker about the state of a possible test system.

Also we should provide the values for the test env-variables which are necessary for the local setup. Should not be a security concern am I right?

**Comment by FabianUntermoser** [comment]
@manuel-pross IMHO not a security concern as long as the production instances use different secrets/passwords/tokens.

A notice in the README or other relevant files to change default secrets is nice to have, but since this is not a commonly self-hosted application, its not required.

**Comment by hanEck** [comment]
Adjustments to the documentation have been done

**Comment by FabianUntermoser** [comment]
As requested @hanEck 

I removed the local-startup.sh script in favour of the existing makefile to setup the project.
I also added another make target to use the `docker-compose.dev.yml` which can be used to only start the application without mounting local files into the containers.

**Review by FabianUntermoser — APPROVED** [review]
As requested @hanEck

I removed the local-startup.sh script in favour of the existing makefile to setup the project.
I also added another make target to use the docker-compose.dev.yml which can be used to only start the application without mounting local files into the containers.

**Pull request merged**
